### ISSUE TITLE
How do you toggle fullscreen?

### ISSUE THREAD

**Issue by boris-glumpler** [enpitsuLin/milkdown-lab#107]
I'm sorry, I might be a bit thick here, but I have no idea how to toggle fullscreen. The `toggleFullscreen` command is not exported, so how do I call it? I'd appreciate any pointers. Cheers!

**Comment by enpitsuLin** [comment]
yes, you are right. the `toggleFullscreen` should be exported for program usage, but now you can use `F11` to toggle or use string literal in commonCtx like:

```ts
editor.ctx.get(commandsCtx).call('ToggleFullscreen',{value:payload}) // payload should be true|false
```

**Comment by enpitsuLin** [comment]
now it be exported on v1.2.3

**Comment by boris-glumpler** [comment]
Thanks!
