### ISSUE TITLE
Update for Milkdown V7

### ISSUE THREAD

**Issue by Nico-Mayer** [enpitsuLin/milkdown-lab#20]
Hey, will these plugins get updates for V7 in the future? :)

**Comment by enpitsuLin** [comment]
I noticed that the Plugin API has changed quite a bit in V7, so this may take some time.

I'll spend some time upgrading, maybe this weekend.

**Comment by enpitsuLin** [comment]
Oh, I have already upgraded the plugin and release it few day ago, so this can be closed now
