### ISSUE TITLE
disabled property of menu item is not treated properly?

### ISSUE THREAD

**Issue by natsuki-engr** [enpitsuLin/milkdown-lab#73]
https://github.com/enpitsuLin/milkdown-lab/blob/c9bdd91207873a5ecbb5688fffdd02876d9ae6a0/packages/plugin-menu/src/menu-plugin.ts#L91C56-L91C56
```js
const isEnabled = item.config.disabled(ctx)
```
In case `disabled` is not `undefined` and it returns `false`, `isEnabled` is `false`.
Isn't it strange?
I feel it should toggle by NOT operator like the following.
```js
const isEnabled = !item.config.disabled(ctx)
```

Because of this, undo and redo buttons are not displayed by default `defaultConfigItems`.

**Comment by enpitsuLin** [comment]
yeah, It's kind of weird. should be fixed 🤣

**Comment by natsuki-engr** [comment]
thank you

**Comment by enpitsuLin** [comment]
@natsuki-engr but undo and redo buttons that don't show maybe because they should add [@milkdown/plugin-history](https://milkdown.dev/docs/api/plugin-history)

see https://github.com/enpitsuLin/milkdown-lab/blob/c9bdd91207873a5ecbb5688fffdd02876d9ae6a0/packages/plugin-menu/src/default-config.ts#L31C13-L31C13

**Comment by natsuki-engr** [comment]
they aren't showed even if plugin-history is loaded in the sample below that ctrl-z and ctrl-y is working in.
https://stackblitz.com/edit/github-xhlvqh

**Comment by enpitsuLin** [comment]
@natsuki-engr my bad, it's a bug, I'll take a look

**Comment by enpitsuLin** [comment]
fixed but still some issue before Milkdown release, you can check #76

**Comment by natsuki-engr** [comment]
Is there any reason you use `"Undo"` as a command key, not `undoCommand.key`?
I think it should works well with `undoCommand.key`.

**Comment by enpitsuLin** [comment]
@natsuki-engr Yeah, you can use `someCommand.key` from another plugin or just use key literal, they should both work

but default-config just provides an  example configuration for people who have no idea how to use plugin-menu, you can write your own config code

**Comment by natsuki-engr** [comment]
@enpitsuLin OK, I got it.
but it is not allowed to use my own config that includes `CmdKey` as `key` property since the type of `key` property in `ButtonConfig` is `string` or `[string, CommandPayload]`.

**Comment by enpitsuLin** [comment]
@natsuki-engr Yeah! you remind me, that it's indeed to add `CmdKey` as a key of `ButtonConfig`, that's my fault

***

I added it to master, I think version should also be after Milkdown release the change, you can just use `//@ts-expect-error` and use `CmdKey` as your wish, this just a type bug

**Comment by natsuki-engr** [comment]
New version 1.2.1 is working fine.
thank you 👍
